include $(MTK_ROOT_BUILD)/Makefile
AUXADC_PLATFORM_DRIVER_DIR :=  $(srctree)/mediatek/platform/$(call lc,$(MTK_PLATFORM))/kernel/drivers/auxadc
obj-y += mt_auxadc.o
ccflags-y  += -I$(AUXADC_PLATFORM_DRIVER_DIR)