/*
 * es515-access.h  --  ES515 Soc Audio access values
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef _ES515_ACCESS_H
#define _ES515_ACCESS_H

#include "escore.h"
#include "es-d202.h"

#define ES_API_WORD(upper, lower) ((upper << 16) | lower)

static struct escore_api_access es515_api_access[ES_API_ADDR_MAX] = {
	[ES_MIC_CONFIG] = {
		.read_msg = { ES_API_WORD(ES_GET_ALGO_PARAM, 0x0002) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_ALGO_PARAM_ID, 0x0002),
			       ES_API_WORD(ES_SET_ALGO_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_AEC_MODE] = {
		.read_msg = { ES_API_WORD(ES_GET_ALGO_PARAM, 0x0003) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_ALGO_PARAM_ID, 0x0003),
			       ES_API_WORD(ES_SET_ALGO_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_VEQ_ENABLE] = {
		.read_msg = { ES_API_WORD(ES_GET_ALGO_PARAM, 0x0009) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_ALGO_PARAM_ID, 0x0009),
			       ES_API_WORD(ES_SET_ALGO_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_ALGORITHM_RESET] = {
		.read_msg = { ES_API_WORD(ES_GET_ALGO_PARAM, 0x001c) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_ALGO_PARAM_ID, 0x001c),
			       ES_API_WORD(ES_SET_ALGO_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTA_WORD_LEN] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0a00) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0a00),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTA_TDM_SLOTS_PER_FRAME] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0a01) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0a01),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTA_TX_DELAY_FROM_FS] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0a02) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0a02),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTA_RX_DELAY_FROM_FS] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0a03) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0a03),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTA_LATCH_EDGE] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0a04) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0a04),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTA_ENDIAN] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0a05) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0a05),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTA_TRISTATE] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0a06) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0a06),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTA_AUDIO_PORT_MODE] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0a07) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0a07),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTA_TDM_ENABLED] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0a08) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0a08),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTA_CLOCK_CONTROL] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0a09) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0a09),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTA_DATA_JUSTIFICATION] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0a0a) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0a0a),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTA_FS_DURATION] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0a0b) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0a0b),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTB_WORD_LEN] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0b00) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0b00),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTB_TDM_SLOTS_PER_FRAME] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0b01) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0b01),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTB_TX_DELAY_FROM_FS] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0b02) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0b02),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTB_RX_DELAY_FROM_FS] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0b03) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0b03),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTB_LATCH_EDGE] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0b04) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0b04),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTB_ENDIAN] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0b05) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0b05),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTB_TRISTATE] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0b06) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0b06),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTB_AUDIO_PORT_MODE] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0b07) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0b07),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTB_TDM_ENABLED] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0b08) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0b08),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTB_CLOCK_CONTROL] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0b09) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0b09),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTB_DATA_JUSTIFICATION] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0b0a) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0b0a),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTB_FS_DURATION] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0b0b) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0b0b),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTC_WORD_LEN] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0c00) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0c00),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTC_TDM_SLOTS_PER_FRAME] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0c01) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0c01),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTC_TX_DELAY_FROM_FS] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0c02) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0c02),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTC_RX_DELAY_FROM_FS] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0c03) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0c03),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTC_LATCH_EDGE] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0c04) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0c04),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTC_ENDIAN] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0c05) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0c05),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTC_TRISTATE] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0c06) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0c06),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTC_AUDIO_PORT_MODE] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0c07) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0c07),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTC_TDM_ENABLED] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0c08) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0c08),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTC_CLOCK_CONTROL] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0c09) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0c09),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTC_DATA_JUSTIFICATION] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0c0a) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0c0a),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_PORTC_FS_DURATION] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0c0b) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0c0b),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SLIMBUS_LINK_MULTI_CHANNEL] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x0900) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x0900),
			       ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_POWER_STATE] = {
		.read_msg = { ES_API_WORD(ES_GET_POWER_STATE, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_POWER_STATE, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 6,
	},
	[ES_STREAMING] = {
		.read_msg = { ES_API_WORD(0x8025, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x9025, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 5,
	},
	[ES_FE_STREAMING] = {
		.read_msg = { ES_API_WORD(0x8028, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x9028, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 8,
	},
	[ES_PRESET] = {
		.read_msg = { ES_API_WORD(0x8031, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x9031, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 2047,
	},
	[ES_ALGO_STATS] = {
		.read_msg = { ES_API_WORD(0x8042, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8042, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 15,
	},
	[ES_ALGO_PROCESSING] = {
		.read_msg = { ES_API_WORD(0x8043, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x801c, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 1,
	},
	[ES_ALGO_SAMPLE_RATE] = {
		.read_msg = { ES_API_WORD(0x804b, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0xb04c, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 5,
	},
	[ES_SMOOTH_RATE] = {
		.read_msg = { ES_API_WORD(0x804d, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x904e, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_CHANGE_STATUS] = {
		.read_msg = { ES_API_WORD(0x804f, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x804f, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 4,
	},
	[ES_DIGITAL_PASS_THROUGH] = {
		.read_msg = { ES_API_WORD(0x8052, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8052, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_DATA_PATH] = {
		.read_msg = { ES_API_WORD(0x805b, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x805a, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_ALGORITHM] = {
		.read_msg = { ES_API_WORD(0x805d, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0xb05c, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 4,
	},
	[ES_MIX_SAMPLE_RATE] = {
		.read_msg = { ES_API_WORD(0x8065, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x805e, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 5,
	},
	[ES_SIGNAL_RMS_PORTA_DIN_LEFT] = {
		.read_msg = { ES_API_WORD(0x8013, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8013, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_RMS_PORTA_DIN_RIGHT] = {
		.read_msg = { ES_API_WORD(0x8013, 0x0001) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8013, 0x0001) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_RMS_PORTA_DOUT_LEFT] = {
		.read_msg = { ES_API_WORD(0x8013, 0x0002) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8013, 0x0002) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_RMS_PORTA_DOUT_RIGHT] = {
		.read_msg = { ES_API_WORD(0x8013, 0x0003) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8013, 0x0003) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_RMS_PORTB_DIN_LEFT] = {
		.read_msg = { ES_API_WORD(0x8013, 0x0004) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8013, 0x0004) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_RMS_PORTB_DIN_RIGHT] = {
		.read_msg = { ES_API_WORD(0x8013, 0x0005) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8013, 0x0005) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_RMS_PORTB_DOUT_LEFT] = {
		.read_msg = { ES_API_WORD(0x8013, 0x0006) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8013, 0x0006) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_RMS_PORTB_DOUT_RIGHT] = {
		.read_msg = { ES_API_WORD(0x8013, 0x0007) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8013, 0x0007) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_RMS_PORTC_DIN_LEFT] = {
		.read_msg = { ES_API_WORD(0x8013, 0x0008) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8013, 0x0008) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_RMS_PORTC_DIN_RIGHT] = {
		.read_msg = { ES_API_WORD(0x8013, 0x0009) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8013, 0x0009) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_RMS_PORTC_DOUT_LEFT] = {
		.read_msg = { ES_API_WORD(0x8013, 0x000a) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8013, 0x000a) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_RMS_PORTC_DOUT_RIGHT] = {
		.read_msg = { ES_API_WORD(0x8013, 0x000b) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8013, 0x000b) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_RMS_PORTD_DIN_LEFT] = {
		.read_msg = { ES_API_WORD(0x8013, 0x000c) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8013, 0x000c) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_RMS_PORTD_DIN_RIGHT] = {
		.read_msg = { ES_API_WORD(0x8013, 0x000d) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8013, 0x000d) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_RMS_PORTD_DOUT_LEFT] = {
		.read_msg = { ES_API_WORD(0x8013, 0x000e) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8013, 0x000e) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_RMS_PORTD_DOUT_RIGHT] = {
		.read_msg = { ES_API_WORD(0x8013, 0x000f) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8013, 0x000f) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_PEAK_PORTA_DIN_LEFT] = {
		.read_msg = { ES_API_WORD(0x8014, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8014, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_PEAK_PORTA_DIN_RIGHT] = {
		.read_msg = { ES_API_WORD(0x8014, 0x0001) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8014, 0x0001) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_PEAK_PORTA_DOUT_LEFT] = {
		.read_msg = { ES_API_WORD(0x8014, 0x0002) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8014, 0x0002) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_PEAK_PORTA_DOUT_RIGHT] = {
		.read_msg = { ES_API_WORD(0x8014, 0x0003) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8014, 0x0003) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_PEAK_PORTB_DIN_LEFT] = {
		.read_msg = { ES_API_WORD(0x8014, 0x0004) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8014, 0x0004) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_PEAK_PORTB_DIN_RIGHT] = {
		.read_msg = { ES_API_WORD(0x8014, 0x0005) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8014, 0x0005) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_PEAK_PORTB_DOUT_LEFT] = {
		.read_msg = { ES_API_WORD(0x8014, 0x0006) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8014, 0x0006) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_PEAK_PORTB_DOUT_RIGHT] = {
		.read_msg = { ES_API_WORD(0x8014, 0x0007) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8014, 0x0007) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_PEAK_PORTC_DIN_LEFT] = {
		.read_msg = { ES_API_WORD(0x8014, 0x0008) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8014, 0x0008) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_PEAK_PORTC_DIN_RIGHT] = {
		.read_msg = { ES_API_WORD(0x8014, 0x0009) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8014, 0x0009) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_PEAK_PORTC_DOUT_LEFT] = {
		.read_msg = { ES_API_WORD(0x8014, 0x000a) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8014, 0x000a) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_PEAK_PORTC_DOUT_RIGHT] = {
		.read_msg = { ES_API_WORD(0x8014, 0x000b) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8014, 0x000b) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_PEAK_PORTD_DIN_LEFT] = {
		.read_msg = { ES_API_WORD(0x8014, 0x000c) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8014, 0x000c) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_PEAK_PORTD_DIN_RIGHT] = {
		.read_msg = { ES_API_WORD(0x8014, 0x000d) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8014, 0x000d) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_PEAK_PORTD_DOUT_LEFT] = {
		.read_msg = { ES_API_WORD(0x8014, 0x000e) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8014, 0x000e) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_SIGNAL_PEAK_PORTD_DOUT_RIGHT] = {
		.read_msg = { ES_API_WORD(0x8014, 0x000f) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8014, 0x000f) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_DIGITAL_GAIN_PRIMARY] = {
		.read_msg = { ES_API_WORD(ES_GET_DIGITAL_GAIN, 0x0001) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DIGITAL_GAIN, 0x0100) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 255,
	},
	[ES_DIGITAL_GAIN_SECONDARY] = {
		.read_msg = { ES_API_WORD(ES_GET_DIGITAL_GAIN, 0x0002) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DIGITAL_GAIN, 0x0200) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 255,
	},
	[ES_DIGITAL_GAIN_TERTIARY] = {
		.read_msg = { ES_API_WORD(ES_GET_DIGITAL_GAIN, 0x0003) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DIGITAL_GAIN, 0x0300) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 255,
	},
	[ES_DIGITAL_GAIN_QUAD] = {
		.read_msg = { ES_API_WORD(ES_GET_DIGITAL_GAIN, 0x0004) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DIGITAL_GAIN, 0x0400) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 255,
	},
	[ES_DIGITAL_GAIN_FEIN] = {
		.read_msg = { ES_API_WORD(ES_GET_DIGITAL_GAIN, 0x0005) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DIGITAL_GAIN, 0x0500) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 255,
	},
	[ES_DIGITAL_GAIN_AUDIN1] = {
		.read_msg = { ES_API_WORD(ES_GET_DIGITAL_GAIN, 0x0006) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DIGITAL_GAIN, 0x0600) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 255,
	},
	[ES_DIGITAL_GAIN_AUDIN2] = {
		.read_msg = { ES_API_WORD(ES_GET_DIGITAL_GAIN, 0x0007) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DIGITAL_GAIN, 0x0700) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 255,
	},
	[ES_DIGITAL_GAIN_AUDIN3] = {
		.read_msg = { ES_API_WORD(ES_GET_DIGITAL_GAIN, 0x0008) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DIGITAL_GAIN, 0x0800) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 255,
	},
	[ES_DIGITAL_GAIN_AUDIN4] = {
		.read_msg = { ES_API_WORD(ES_GET_DIGITAL_GAIN, 0x0009) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DIGITAL_GAIN, 0x0900) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 255,
	},
	[ES_DIGITAL_GAIN_UITONE1] = {
		.read_msg = { ES_API_WORD(ES_GET_DIGITAL_GAIN, 0x000A) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DIGITAL_GAIN, 0x0a00) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 255,
	},
	[ES_DIGITAL_GAIN_UITONE2] = {
		.read_msg = { ES_API_WORD(ES_GET_DIGITAL_GAIN, 0x000B) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DIGITAL_GAIN, 0x0b00) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 255,
	},
	[ES_AECREF1_GAIN] = {
		.read_msg = { ES_API_WORD(ES_GET_DIGITAL_GAIN, 0x000C) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DIGITAL_GAIN, 0x0c00) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 255,
	},
	[ES_DIGITAL_GAIN_CSOUT] = {
		.read_msg = { ES_API_WORD(ES_GET_DIGITAL_GAIN, 0x0010) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DIGITAL_GAIN, 0x1000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 255,
	},
	[ES_DIGITAL_GAIN_FEOUT1] = {
		.read_msg = { ES_API_WORD(ES_GET_DIGITAL_GAIN, 0x0011) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DIGITAL_GAIN, 0x1100) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 255,
	},
	[ES_DIGITAL_GAIN_FEOUT2] = {
		.read_msg = { ES_API_WORD(ES_GET_DIGITAL_GAIN, 0x0012) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DIGITAL_GAIN, 0x1200) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 255,
	},
	[ES_DIGITAL_GAIN_AUDOUT1] = {
		.read_msg = { ES_API_WORD(ES_GET_DIGITAL_GAIN, 0x0013) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DIGITAL_GAIN, 0x1300) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 255,
	},
	[ES_DIGITAL_GAIN_AUDOUT2] = {
		.read_msg = { ES_API_WORD(ES_GET_DIGITAL_GAIN, 0x0014) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DIGITAL_GAIN, 0x1400) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 255,
	},
	[ES_DIGITAL_GAIN_AUDOUT3] = {
		.read_msg = { ES_API_WORD(ES_GET_DIGITAL_GAIN, 0x0015) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DIGITAL_GAIN, 0x1500) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 255,
	},
	[ES_DIGITAL_GAIN_AUDOUT4] = {
		.read_msg = { ES_API_WORD(ES_GET_DIGITAL_GAIN, 0x0016) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DIGITAL_GAIN, 0x1600) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 255,
	},
	[ES_PORTA_TIMING] = {
		.read_msg = { ES_API_WORD(ES_GET_PORT_TIMING, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_PORT_TIMING, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 15,
	},
	[ES_PORTB_TIMING] = {
		.read_msg = { ES_API_WORD(ES_GET_PORT_TIMING, 0x1000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_PORT_TIMING, 0x1000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 15,
	},
	[ES_PORTC_TIMING] = {
		.read_msg = { ES_API_WORD(ES_GET_PORT_TIMING, 0x2000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_PORT_TIMING, 0x2000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 15,
	},
	[ES_PORTD_TIMING] = {
		.read_msg = { ES_API_WORD(ES_GET_PORT_TIMING, 0x3000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_PORT_TIMING, 0x3000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 15,
	},
	[ES_FLUSH] = {
		.read_msg = { ES_API_WORD(0x805A, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8059, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 0,
	},
	[ES_FW_FIRST_CHAR] = {
		.read_msg = { ES_API_WORD(0x8020, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8020, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 255,
	},
	[ES_FW_NEXT_CHAR] = {
		.read_msg = { ES_API_WORD(0x8021, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8021, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 255,
	},
	[ES_SET_CODEC_ADDR] = {
		.write_msg = { ES_API_WORD(0x907A, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 80, /* MAX A212 register addr 0x50 */
	},
	[ES_CODEC_VALUE] = {
		.read_msg = { ES_API_WORD(0x807B, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x907C, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 65535,
	},
	[ES_EVENT_RESPONSE] = {
		.read_msg = { ES_API_WORD(0x801a, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x901a, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 4,
	},
	[ES_VOICE_SENSE_ENABLE] = {
		.read_msg = { ES_API_WORD(0x8000, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8000, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 1,
	},
	[ES_VOICE_SENSE_SET_KEYWORD] = {
		.read_msg = { ES_API_WORD(0x8000, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8000, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 4,
	},
	[ES_VOICE_SENSE_EVENT] = {
		.read_msg = { ES_API_WORD(0x806d, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8000, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 2,
	},
	[ES_VOICE_SENSE_TRAINING_MODE] = {
		.read_msg = { ES_API_WORD(ES_GET_ALGO_PARAM, 0x5003) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_ALGO_PARAM_ID, 0x5003),
				   ES_API_WORD(ES_SET_ALGO_PARAM, 0x0000)
		},
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 2,
	},
	[ES_VOICE_SENSE_TRAINING_RECORD] = {
		.read_msg = { ES_API_WORD(ES_GET_ALGO_PARAM, 0x5006) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_ALGO_PARAM_ID, 0x5006),
			       ES_API_WORD(ES_SET_ALGO_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 1,
	},
	[ES_VOICE_SENSE_TRAINING_STATUS] = {
		.read_msg = { ES_API_WORD(0x8000, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8000, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 1,
	},
	[ES_VOICE_SENSE_DEMO_ENABLE] = {
		.read_msg = { ES_API_WORD(0x8000, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x8000, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 1,
	},
	[ES_GET_SYS_INTERRUPT_STATUS] = {
		.read_msg = { ES_API_WORD(0x8053, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x9053, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 0,
	},
	[ES_CLEAR_SYS_INTERRUPT_STATUS] = {
		.read_msg = { ES_API_WORD(0x8057, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x9057, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 0x3FFF,
	},
	[ES_ACCESSORY_DET_CONFIG] = {
		.read_msg = { ES_API_WORD(0x8055, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x9056, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 1,
	},
	[ES_ACCESSORY_DET_STATUS] = {
		.read_msg = { ES_API_WORD(0x8054, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(0x9054, 0x0000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = 1,
	},
	[ES_BUTTON_DETECTION_ENABLE] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x1f30) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x1f30),
			ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 1,
	},
	[ES_BUTTON_SERIAL_CONFIG] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x1f31) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x1f31),
			ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 1,
	},
	[ES_BUTTON_PARALLEL_CONFIG] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x1f32) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x1f32),
			ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 1,
	},
	[ES_BUTTON_DETECTION_RATE] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x1f33) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x1f33),
			ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 3,
	},
	[ES_BUTTON_PRESS_SETTLING_TIME] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x1f34) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x1f34),
			ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 7,
	},
	[ES_BUTTON_BOUNCE_TIME] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x1f35) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x1f35),
			ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 11,
	},
	[ES_BUTTON_DETECTION_LONG_PRESS_TIME] = {
		.read_msg = { ES_API_WORD(ES_GET_DEV_PARAM, 0x1f36) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_DEV_PARAM_ID, 0x1f36),
			ES_API_WORD(ES_SET_DEV_PARAM, 0x0000) },
		.write_msg_len = 8,
		.val_shift = 0,
		.val_max = 15,
	},
	[ES_PRIMARY_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x0400) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x0400) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_INPUT_PORT,
	},
	[ES_SECONDARY_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x0800) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x0800) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_INPUT_PORT,
	},
	[ES_TERITARY_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x0c00) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x0c00) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_INPUT_PORT,
	},
	[ES_AECREF1_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x3000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x3000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_INPUT_PORT,
	},
	[ES_FEIN_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x1400) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x1400) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_INPUT_PORT,
	},
	[ES_UITONE1_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x2800) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x2800) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_INPUT_PORT,
	},
	[ES_UITONE2_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x2c00) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x2c00) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_INPUT_PORT,
	},
	[ES_AUDIN1_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x1800) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x1800) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_INPUT_PORT,
	},
	[ES_AUDIN2_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x1c00) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x1c00) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_INPUT_PORT,
	},
	[ES_AUDIN3_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x2000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x2000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_INPUT_PORT,
	},
	[ES_AUDIN4_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x2400) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x2400) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_INPUT_PORT,
	},
	[ES_PCM0_0_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x0000) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x4000) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_PATH_TYPE,
	},
	[ES_PCM0_1_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x0001) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x4001) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_PATH_TYPE,
	},
	[ES_PCM0_2_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x0002) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x4002) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_PATH_TYPE,
	},
	[ES_PCM0_3_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x0003) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x4003) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_PATH_TYPE,
	},
	[ES_PCM1_0_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x0020) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x4020) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_PATH_TYPE,
	},
	[ES_PCM1_1_MUX] = {
		.read_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x0021) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x4021) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_PATH_TYPE,
	},
	[ES_PCM1_2_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x0022) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x4022) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_PATH_TYPE,
	},
	[ES_PCM1_3_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x0023) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x4023) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_PATH_TYPE,
	},
	[ES_PCM2_0_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x0040) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x4040) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_PATH_TYPE,
	},
	[ES_PCM2_1_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x0041) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x4041) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_PATH_TYPE,
	},
	[ES_PCM2_2_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x0042) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x4042) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_PATH_TYPE,
	},
	[ES_PCM2_3_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x0043) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x4043) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_PATH_TYPE,
	},
	[ES_SBUSTX0_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x00aa) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x40aa) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_PATH_TYPE,
	},
	[ES_SBUSTX1_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x00ab) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x40ab) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_PATH_TYPE,
	},
	[ES_SBUSTX2_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x00ac) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x40ac) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_PATH_TYPE,
	},
	[ES_SBUSTX3_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x00ad) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x40ad) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_PATH_TYPE,
	},
	[ES_SBUSTX4_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x00ae) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x40ae) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_PATH_TYPE,
	},
	[ES_SBUSTX5_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD, 0x00af) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD, 0x40af) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_PATH_TYPE,
	},
	[ES_DAC0_0_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD,
				DATA_PATH(0, DAC0, 0)) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD,
				DATA_PATH(0, DAC0, 0)) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_PATH_TYPE,
	},
	[ES_DAC0_1_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD,
				DATA_PATH(0, DAC0, 1)) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD,
				DATA_PATH(0, DAC0, 1)) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_PATH_TYPE,
	},
	[ES_DAC1_0_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD,
				DATA_PATH(0, DAC1, 0)) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD,
				DATA_PATH(0, DAC1, 0)) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_PATH_TYPE,
	},
	[ES_DAC1_1_MUX] = {
		.read_msg = { ES_API_WORD(ES_GET_MUX_CMD,
				DATA_PATH(0, DAC1, 1)) },
		.read_msg_len = 4,
		.write_msg = { ES_API_WORD(ES_SET_MUX_CMD,
				DATA_PATH(0, DAC1, 1)) },
		.write_msg_len = 4,
		.val_shift = 0,
		.val_max = MAX_PATH_TYPE,
	},

};

#endif /* _ES_ACCESS_H */
