#ifndef _DRV_CONFIG_H_
#define _DRV_CONFIG_H_

#define CONFIG_DRV_LINUX_DATA_CONSISTENCY 0
#define CONFIG_DRV_HIGH_BITRATE_SPECIAL_PROC 0
#define CONFIG_DRV_SUPPORT_RM 0
#define CONFIG_DRAM256_MODEL 0
#define CONFIG_DRV_3D_SUPPORT 0
#define CONFIG_DRV_OMX_SUPPORT 0
#define CONFIG_DRV_SUPPORT_DVD_AUDIO 0
#define CONFIG_DRV_FTS_SUPPORT 0
#define CONFIG_DRV_ONLY 0
#define CONFIG_DRV_VERIFY_SUPPORT 1
#define CONFIG_SECTION_BUILD_LINUX_KO 0
#define CONFIG_DRV_VIRTUAL_ADDR 0

#define VDEC_MVC_SUPPORT 0
#define VDEC_DDR3_SUPPORT 0
#define VDEC_TEST_ADDSWAP 0
#define VDEC_MC_NBM_OFF 0

#endif // _DRV_CONFIG_H_
